/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp --verbose dbus-interface.xml -p DbusInterface -i CustomTypes.h
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "DbusInterface.h"

/*
 * Implementation of interface class NetConnmanIwdAdapterInterface
 */

NetConnmanIwdAdapterInterface::NetConnmanIwdAdapterInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdAdapterInterface::~NetConnmanIwdAdapterInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdAgentManagerInterface
 */

NetConnmanIwdAgentManagerInterface::NetConnmanIwdAgentManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdAgentManagerInterface::~NetConnmanIwdAgentManagerInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdDeviceInterface
 */

NetConnmanIwdDeviceInterface::NetConnmanIwdDeviceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdDeviceInterface::~NetConnmanIwdDeviceInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdKnownNetworkInterface
 */

NetConnmanIwdKnownNetworkInterface::NetConnmanIwdKnownNetworkInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdKnownNetworkInterface::~NetConnmanIwdKnownNetworkInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdNetworkInterface
 */

NetConnmanIwdNetworkInterface::NetConnmanIwdNetworkInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdNetworkInterface::~NetConnmanIwdNetworkInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdSignalLevelAgentInterface
 */

NetConnmanIwdSignalLevelAgentInterface::NetConnmanIwdSignalLevelAgentInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdSignalLevelAgentInterface::~NetConnmanIwdSignalLevelAgentInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdSimpleConfigurationInterface
 */

NetConnmanIwdSimpleConfigurationInterface::NetConnmanIwdSimpleConfigurationInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdSimpleConfigurationInterface::~NetConnmanIwdSimpleConfigurationInterface()
{
}

/*
 * Implementation of interface class NetConnmanIwdStationInterface
 */

NetConnmanIwdStationInterface::NetConnmanIwdStationInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

NetConnmanIwdStationInterface::~NetConnmanIwdStationInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusObjectManagerInterface
 */

OrgFreedesktopDBusObjectManagerInterface::OrgFreedesktopDBusObjectManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusObjectManagerInterface::~OrgFreedesktopDBusObjectManagerInterface()
{
}

/*
 * Implementation of interface class OrgFreedesktopDBusPropertiesInterface
 */

OrgFreedesktopDBusPropertiesInterface::OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPropertiesInterface::~OrgFreedesktopDBusPropertiesInterface()
{
}

